stages:
  train_model:
    cmd: cd src && python main.py
    deps:
    - data/uniref50_sample_2.fasta
    - src/main.py
    params:
    - model.n_clusters
    outs:
    - models/sequence_model.pkl
    metrics:
    - metrics.json
  run_unit_tests:
    cmd: set PYTHONPATH=src && pytest --tb=short | tee tests/test_report.txt
    deps:
    - tests/
    - src/
    outs:
    - tests/test_report.txt
